<a href="https://colab.research.google.com/github/darkmochalover/DS_TermProject_AL2/blob/main/logistic_regression_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dictionary

In [ ]:
# Data Path
raw_data_path = "/content/drive/MyDrive/DS_TermProject/data/combined_mbti_df.csv"
# data_path = "data/preprocessed_mbti_data.csv"


audio_qualities = [
    'danceability_mean',
    'valence_mean',
    'energy_mean',
    'loudness_mean',
    'acousticness_mean',
    'instrumentalness_mean',
    'liveness_mean',
]

# 장조/단조 (Major/Minor)
all_tones = [
    'Cminor_count', 'CMajor_count', 'C#/Dbminor_count', 'C#/DbMajor_count',
    'DMajor_count', 'D#_EbMajor_count', 'Eminor_count', 'EMajor_count',
    'Fminor_count', 'FMajor_count', 'F#/Gbminor_count', 'GMajor_count',
    'G#/Abminor_count', 'G#/AbMajor_count', 'Aminor_count', 'AMajor_count',
    'A#/Bbminor_count', 'BMajor_count', 'Dminor_count', 'D#_Ebminor_count',
    'Gminor_count', 'A#/BbMajor_count', 'F#/GbMajor_count', 'Bminor_count'
]

major_tones = [
    'CMajor_count', 'C#/DbMajor_count',
    'DMajor_count', 'D#_EbMajor_count', 
    'EMajor_count',
    'FMajor_count', 
    'GMajor_count', 'G#/AbMajor_count', 
    'AMajor_count', 'BMajor_count', 'A#/BbMajor_count', 
    'F#/GbMajor_count'
]
minor_tones = [
    'Cminor_count', 'C#/Dbminor_count', 
    'Eminor_count', 
    'Fminor_count', 'F#/Gbminor_count', 
    'G#/Abminor_count',  
    'Aminor_count', 'A#/Bbminor_count', 
    'Dminor_count', 'D#_Ebminor_count',
    'Gminor_count', 
    'Bminor_count'
]


# 열 이름을 바꾸기 위해 리스트로 저장함
renamed_columns =  [
    'danceability',
    'valence',
    'energy',
    'loudness',
    'acousticness',
    'instrumentalness',
    'liveness'
]


Install WandB

In [ ]:
!pip install -qU wandb

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler
from imblearn.over_sampling import SMOTE

import itertools

import wandb
import random

Step 1: Import W&B and Login

In [ ]:
import wandb
from wandb.keras import WandbMetricsLogger, WandbModelCheckpoint, WandbEvalCallback

In [ ]:
encoder_list = ['LabelEncoder','OneHotEncoder']
scaler_list = ['StandardScaler', 'MinMaxScaler', 'RobustScaler', 'No Scale']
test_size_list = [0.3, 0.2, 0.1]
do_smote = ['True', 'False']

In [ ]:
config = {
        'encoder' : 'LabelEncoder',
        'scaler' : 'StandardScaler',
        'test_size' : 0.3,
        "do_smote" : True
    }

# start a new wandb run to track this script
wandb.init(
    # set the wandb project where this run will be logged
    project="regression",
    
    # track hyperparameters and run metadata
    config = config
)

config=wandb.config


Data Loading

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

raw_data_path = '/content/drive/MyDrive/DS_TermProject/data/combined_mbti_df.csv'
df = pd.read_csv(raw_data_path)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Feature Engineering

In [ ]:
# Subset only measures of centers
X = df.iloc[: , :22] # 처음 22개 열을 선택해서 저장
X = df[audio_qualities] # 오디오 품질과 해당 열이 있는 열을 선택해서 저장


categories = renamed_columns[:]
X.columns = renamed_columns


# 장조/단조의 개수의 합을 계산해서 저장 (C장조, D단조, .. 이렇게 따로 계산되는거 말고, 위에 지정된 list 이용해서 sum값 넣어줌)
X['major_count'] = df[major_tones].sum(axis=1).astype('int64')
X['minor_count'] = df[minor_tones].sum(axis=1).astype('int64')

<ipython-input-26-482ca4c8bc7c>:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['major_count'] = df[major_tones].sum(axis=1).astype('int64')
<ipython-input-26-482ca4c8bc7c>:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['minor_count'] = df[minor_tones].sum(axis=1).astype('int64')


## Encoding & Scaling Function

In [ ]:
def Encoding(df, encoding_method):
    df = df.copy()

    if(encoding_method == 'LabelEncoder'):
        encoder = LabelEncoder()
        target = encoder.fit_transform(df[['mbti']])
        

    if(encoding_method == 'OneHotEncoder'):
        encoder = OneHotEncoder(sparse=False)
        target = encoder.fit_transform(df[['mbti']])

    return target

def Scaling(scale_method, X_train, X_test):
    if( scale_method == 'No Scale'):
        return X_train, X_test

    elif(scale_method == 'StandardScaler'):
        scaler = StandardScaler()

    elif(scale_method == 'MinMaxScaler'):
        scaler = MinMaxScaler()

    elif(scale_method == 'RobustScaler'):
        scaler = RobustScaler()


    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.fit_transform(X_test)

    return X_train_scaled, X_test_scaled


In [ ]:
# If X and y have different shapes, adjust them accordingly
if X.shape[0] > y.shape[0]:
    X = X[:y.shape[0], :]
else:
    y = y[:X.shape[0]]

# Print the adjusted shape of X and y
print("Adjusted X shape:", X.shape)
print("Adjusted y shape:", y.shape)

Adjusted X shape: (4081, 9)
Adjusted y shape: (4081,)


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, recall_score, precision_score
import itertools
import wandb
import numpy as np

# Grid search hyperparameters
param_grid = {
    'penalty': ['l1', 'l2'],
    'C': [0.1, 1.0, 10.0]
}

# Define the combinations of hyperparameters
encoder_list = ['LabelEncoder', 'OneHotEncoder']
scaler_list = ['StandardScaler', 'MinMaxScaler', 'RobustScaler', 'No Scale']
test_size_list = [0.3, 0.2, 0.1]
do_smote_list = [True, False]

combinations = list(itertools.product(encoder_list, scaler_list, test_size_list, do_smote_list))

for encoder, scaler, test_size, do_smote in combinations:
    # Print the hyperparameter settings
    print(f"Encoder: {encoder}, Scaler: {scaler}, Test Size: {test_size}, SMOTE: {do_smote}")
    wandb.init(project='logistic_regression', config={
        'encoder': encoder,
        'scaler': scaler,
        'test_size': test_size,
        'do_smote': do_smote
    })

    # Split the dataset into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=5, test_size=test_size)

    # Apply the specified encoder and scaler
    if encoder == 'LabelEncoder':
        encoder = LabelEncoder()
        y_train = encoder.fit_transform(y_train)
        y_test = encoder.transform(y_test)
    elif encoder == 'OneHotEncoder':
        encoder = OneHotEncoder()
        y_train = encoder.fit_transform(y_train.reshape(-1, 1)).toarray()
        y_test = encoder.transform(y_test.reshape(-1, 1)).toarray()

    if scaler == 'StandardScaler':
        scaler = StandardScaler()
        X_train = scaler.fit_transform(X_train)
        X_test = scaler.transform(X_test)
    elif scaler == 'MinMaxScaler':
        scaler = MinMaxScaler()
        X_train = scaler.fit_transform(X_train)
        X_test = scaler.transform(X_test)
    elif scaler == 'RobustScaler':
        scaler = RobustScaler()
        X_train = scaler.fit_transform(X_train)
        X_test = scaler.transform(X_test)
    elif scaler == 'No Scale':
        # No scaling
        pass

    # Perform SMOTE if enabled
    if do_smote:
        smote = SMOTE(random_state=42)
        X_train, y_train = smote.fit_resample(X_train, y_train)

    # Create and fit the logistic regression model
    model = LogisticRegression(random_state=42)
    model.fit(X_train, y_train)

    # Make predictions on the test set
    predictions = model.predict(X_test)

    # Calculate evaluation metrics
    accuracy = accuracy_score(y_test, predictions)
    cm = confusion_matrix(y_test, predictions)
    f1 = f1_score(y_test, predictions, average='macro')
    recall = recall_score(y_test, predictions, average='macro')
    precision = precision_score(y_test, predictions, average='macro')

    # Log the evaluation metrics to WandB
    wandb.log({'Accuracy': accuracy})
    wandb.log({'Confusion Matrix': cm})
    wandb.log({'F1 Score': f1})
    wandb.log({'Recall': recall})
    wandb.log({'Precision': precision})

    # Print the evaluation metrics
    print("Accuracy:", accuracy)
    print("Confusion Matrix:\n", cm)
    print("F1 Score:", f1)
    print("Recall:", recall)
    print("Precision:", precision)


Encoder: LabelEncoder, Scaler: StandardScaler, Test Size: 0.3, SMOTE: True


Accuracy: 0.21551020408163266
Confusion Matrix:
 [[12 10  4  1 12  2  5  3  0  5  3  5  6  4  2  4]
 [ 3 25  0  6 11 10  7  2  2  2  3  1  4  3  2  2]
 [ 2  1 26 11  5  1 12  9  2  0  9  1  1  0  0  6]
 [ 2  4  4 37  3  8 11  9  1  1  3  3  0  0  1  7]
 [ 1  7  0  2  5  1  2  1  1  3  2  0  5  0  1  1]
 [ 1 12  5  2 10 14  3  9  1  2  2  1  5  0  1  0]
 [ 1  5  7  3  2  2  7  3  0  0  0  3  3  1  3  1]
 [ 3  5 13 13  7 12  6 19  1  0  9  2  2  2  0  5]
 [ 6  5  0  1  2  0  2  0 17 13 13  7 20  2  5  3]
 [ 9  5  1  3  1  1  4  2 15 13  5  6 16  1  4  3]
 [ 3  3  9  9  2  0  3  2  7  1 22 18  4  0  9  2]
 [ 6  6  5  4  3  2  3  3  2  3  8 25  5  4  6  5]
 [ 3  7  0  0  4  1  1  1  9  6  2  4 18  3  2  2]
 [ 1  3  3  2  5  3  7  0  6  4 10  2  9  7  3  5]
 [10  1  4  0  6  1  2  0  5  4  2  6  7  2  3  6]
 [ 0  8 10 11  2  3  6  3  2  2  8  5  4  1  4 14]]
F1 Score: 0.20181350905402895
Recall: 0.2072490218838857
Precision: 0.21017680242879336
Encoder: LabelEncoder, Scaler: StandardScaler,

Accuracy: 0.21959183673469387
Confusion Matrix:
 [[19 15  6  1  0  3  0  3  0  6  3  4  5  8  1  4]
 [ 7 31  3  8  0 11  0  5  2  2  4  1  2  5  0  2]
 [ 4  1 35 14  0  3  0  8  2  1  8  0  0  2  0  8]
 [ 3  7 12 40  0  6  0 11  1  1  3  4  0  0  0  6]
 [ 4 10  2  2  1  0  0  1  1  2  2  0  4  2  0  1]
 [ 5 20  7  3  1  7  0 12  1  2  2  1  4  3  0  0]
 [ 2  8 12  3  0  0  0  5  2  1  1  3  1  2  0  1]
 [ 6 10 17 17  0  7  0 19  1  0  9  2  2  2  0  7]
 [ 9  6  0  1  0  1  0  0 21 13 15  7 14  6  0  3]
 [14  8  3  3  0  1  1  2 16 11  5  6 11  5  0  3]
 [ 5  5 10 10  0  0  0  2  7  1 27 18  2  5  0  2]
 [11  8  6  2  0  0  0  4  3  4 10 24  2  6  2  8]
 [10  9  0  0  0  1  0  1  9  9  3  5  9  4  2  1]
 [ 5  3  7  4  0  2  0  0  8  5 11  3  7 10  0  5]
 [18  1  6  0  0  1  0  0  5  4  2  6  6  4  0  6]
 [ 5 11 16 10  0  1  0  3  1  3  9  4  2  3  0 15]]
F1 Score: 0.18237838114177587
Recall: 0.19614913369257425
Precision: 0.20452633042209173
Encoder: LabelEncoder, Scaler: StandardScaler

Accuracy: 0.22031823745410037
Confusion Matrix:
 [[10  5  1  1  3  2  5  3  0  1  0  4  5  3  1  3]
 [ 2 17  0  3  6  4  4  3  0  2  3  0  3  1  2  2]
 [ 0  0 17  8  4  1  6  8  1  0  5  0  1  0  2  3]
 [ 2  3  2 23  1  3  8  7  1  1  2  3  0  0  1  5]
 [ 1  4  0  1  6  0  1  0  0  0  1  0  3  0  0  1]
 [ 1 10  2  3  7  8  2  8  1  0  2  0  4  0  0  0]
 [ 2  4  2  1  2  2  4  2  0  0  0  3  2  1  2  0]
 [ 1  6  6 10  4  9  4 15  1  0  6  2  1  2  0  1]
 [ 3  2  0  1  1  0  2  0 12 12  8  5 14  0  3  2]
 [ 9  4  1  2  1  1  3  1 11  8  3  3  8  0  2  1]
 [ 2  4  5  6  1  0  3  1  3  3 13 10  2  0  5  1]
 [ 7  3  5  0  2  2  3  1  2  1  7 18  4  3  3  4]
 [ 3  7  0  0  5  1  0  1  7  2  3  3 13  1  1  1]
 [ 0  1  1  3  5  3  5  0  6  2  5  2  9  5  2  4]
 [ 6  1  2  0  7  0  0  0  4  3  1  5  4  0  2  3]
 [ 0  1  5  8  2  1 10  4  2  1  4  3  2  0  1  9]]
F1 Score: 0.20801544166548164
Recall: 0.21814930769175372
Precision: 0.22034260545251325
Encoder: LabelEncoder, Scaler: StandardScaler

Accuracy: 0.21909424724602203
Confusion Matrix:
 [[13  7  2  2  0  2  0  3  0  1  0  5  4  6  0  2]
 [ 5 18  2  4  0  5  0  6  0  2  3  0  1  3  1  2]
 [ 1  0 23  9  0  3  0  7  2  0  5  0  1  2  0  3]
 [ 2  5  8 25  0  3  0  6  1  1  2  4  0  0  0  5]
 [ 5  5  0  1  0  0  0  0  0  0  1  0  3  2  0  1]
 [ 4 15  3  5  1  3  0  9  1  0  2  0  4  1  0  0]
 [ 2  6  5  3  0  0  0  2  1  2  0  3  0  2  1  0]
 [ 3  8 10 12  0  2  0 18  1  0  6  2  1  1  1  3]
 [ 3  3  0  1  0  1  0  0 14 15 10  5  7  3  1  2]
 [11  6  1  2  0  1  1  2 13  7  4  3  6  0  0  1]
 [ 5  5  8  5  0  0  0  1  3  3 15  9  0  3  0  2]
 [ 9  5  6  0  0  0  0  2  3  3  7 19  2  3  1  5]
 [10  7  0  0  0  1  0  1  7  6  3  3  6  2  1  1]
 [ 3  2  2  4  0  2  0  0  6  5  7  3  6  9  0  4]
 [13  2  2  0  0  0  0  0  4  3  1  7  3  0  0  3]
 [ 6  2 12  9  0  1  0  4  2  1  4  2  1  0  0  9]]
F1 Score: 0.17902625463666044
Recall: 0.19444609111645536
Precision: 0.1749887754387271
Encoder: LabelEncoder, Scaler: StandardScaler,

Accuracy: 0.20537897310513448
Confusion Matrix:
 [[ 2  0  1  1  3  2  1  1  0  0  0  1  3  2  0  1]
 [ 1  7  1  0  4  3  1  3  0  0  1  0  1  0  0  0]
 [ 0  0  8  7  1  1  2  4  0  0  2  0  0  0  2  2]
 [ 0  2  3 13  0  1  1  1  0  1  0  1  0  0  0  1]
 [ 0  3  0  1  4  0  0  0  0  0  0  0  2  0  0  1]
 [ 1  6  0  1  5  4  1  6  0  0  1  0  0  0  1  0]
 [ 1  3  2  0  1  1  3  1  0  1  0  2  0  0  0  0]
 [ 1  2  6  8  4  4  1  6  0  0  1  0  0  1  0  1]
 [ 0  1  0  1  1  0  1  0  6  5  3  3  7  0  1  0]
 [ 2  2  1  2  0  0  2  0  8  3  1  2  3  1  1  1]
 [ 2  2  2  2  2  0  1  1  0  1  4  8  0  0  2  0]
 [ 1  1  3  1  1  1  3  0  2  1  3 11  2  3  5  2]
 [ 0  3  0  0  1  0  1  1  4  2  3  3  8  1  1  1]
 [ 0  1  2  1  3  2  2  0  4  1  2  2  5  3  3  2]
 [ 2  1  2  0  2  0  0  0  2  2  0  2  3  0  1  3]
 [ 0  2  6  4  0  0  3  1  0  0  2  2  0  0  1  1]]
F1 Score: 0.1886512603595123
Recall: 0.20821571468123193
Precision: 0.19278242675867274
Encoder: LabelEncoder, Scaler: StandardScaler,

Accuracy: 0.2078239608801956
Confusion Matrix:
 [[ 5  4  1  2  0  1  0  1  0  0  0  1  1  1  0  1]
 [ 2  8  2  0  0  3  0  4  0  0  1  0  1  0  0  1]
 [ 0  0 10  8  0  1  0  4  1  0  2  0  0  1  0  2]
 [ 0  2  3 15  0  0  0  1  0  1  0  1  0  0  0  1]
 [ 0  6  0  1  0  0  0  0  0  1  0  0  2  0  0  1]
 [ 3  9  1  2  0  2  0  7  0  0  1  0  0  1  0  0]
 [ 1  5  4  0  0  0  0  2  0  1  0  2  0  0  0  0]
 [ 1  6  6  8  0  3  0  7  0  0  1  0  0  1  0  2]
 [ 0  2  0  1  0  0  0  0  7  8  4  3  3  1  0  0]
 [ 3  3  2  2  0  0  0  0 11  3  1  2  1  0  0  1]
 [ 4  3  2  2  0  0  0  1  0  1  6  6  0  1  0  1]
 [ 4  2  4  2  0  0  0  0  3  2  4 11  1  3  1  3]
 [ 5  3  0  0  0  0  0  1  5  4  4  3  2  1  0  1]
 [ 0  1  2  2  0  2  0  0  5  2  5  2  4  6  0  2]
 [ 4  2  2  0  0  0  0  0  2  3  0  3  1  0  0  3]
 [ 1  2  7  5  0  0  0  1  0  0  2  1  0  0  0  3]]
F1 Score: 0.16836607263413494
Recall: 0.19483512177477696
Precision: 0.1675217608393217
Encoder: LabelEncoder, Scaler: MinMaxScaler, Te

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy: 0.19183673469387755
Confusion Matrix:
 [[ 5 13  4  3 12  9  4  1  3  4  3  3  9  4  1  0]
 [ 0 29  4  6 11 10  2  1  6  1  3  2  4  0  2  2]
 [ 0  3 25 14  6  6 10  6  2  0  6  1  1  1  0  5]
 [ 0  6  9 31  3 16  4  7  0  3  2  4  0  1  0  8]
 [ 0  7  2  1  4  3  1  2  2  1  1  0  5  0  2  1]
 [ 1 12  4  2 10 16  4  6  2  2  2  1  6  0  0  0]
 [ 1  4 10  4  3  3  4  1  0  0  1  3  3  0  3  1]
 [ 1  7 14 15  7 22  3 10  3  0 10  2  1  0  0  4]
 [ 2  7  1  0  2  2  0  0 21 10 11  7 24  4  4  1]
 [ 4  5  2  5  1  3  1  1 17 12  5  7 20  0  5  1]
 [ 1  5  9  6  4  3  1  1 12  0 22 17  4  0  7  2]
 [ 0  8  6  1  3  3  2  3  6  4  9 25  6  2  9  3]
 [ 2  9  0  1  5  1  0  0  5  7  3  6 19  0  4  1]
 [ 0  3  7  3  7  4  4  1  5  2  9  4 11  3  4  3]
 [ 4  2  6  0  6  2  1  0  7  3  3  9 10  1  3  2]
 [ 0 11 12 11  5  7  3  1  1  3  7  6  5  1  4  6]]
F1 Score: 0.17070614213316743
Recall: 0.18286456922084857
Precision: 0.18650097679298208
Encoder: LabelEncoder, Scaler: MinMaxScaler, 

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.21306122448979592
Confusion Matrix:
 [[14 18  9  3  0  2  0  3  3  4  3  2  5 10  0  2]
 [ 4 33  7  5  0  9  0  6  3  0  3  2  2  6  1  2]
 [ 2  3 41 10  0  3  0  9  2  0  6  1  1  2  0  6]
 [ 2  7 14 33  0  6  0 14  0  3  2  4  0  1  0  8]
 [ 5  7  3  1  0  1  0  4  2  1  1  0  4  2  0  1]
 [ 5 21  8  3  0  7  0 12  2  3  2  1  4  0  0  0]
 [ 2  7 14  3  0  1  0  4  1  0  1  4  2  1  1  0]
 [ 6 12 21 13  0  6  0 19  3  0  9  2  1  2  0  5]
 [ 4  8  1  0  0  1  0  1 24 12 13  8 16  7  0  1]
 [11  8  4  4  0  0  0  2 19 13  6  7 12  2  0  1]
 [ 4  7 13  4  0  0  0  4 12  0 23 18  2  5  0  2]
 [ 3 10  8  0  0  0  0  6  7  5  9 27  4  6  1  4]
 [ 9  9  0  0  0  1  0  0  8  8  4  6 11  3  2  2]
 [ 4  4 11  2  0  3  0  3  7  2 12  4  6  9  0  3]
 [13  5  7  0  0  1  0  0 10  3  3  6  6  3  0  2]
 [ 1 12 20 10  0  1  0  4  1  4  9  7  3  4  0  7]]
F1 Score: 0.1718770542730076
Recall: 0.18925038403267802
Precision: 0.16836172067967958
Encoder: LabelEncoder, Scaler: MinMaxScaler, T

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy: 0.19461444308445533
Confusion Matrix:
 [[ 3  6  2  1  5  4  3  1  2  2  0  3  9  3  1  2]
 [ 0 19  2  6  6  3  0  2  1  1  3  2  3  1  2  1]
 [ 0  1 13 10  3  2 11  6  2  0  4  0  1  1  0  2]
 [ 1  4  3 23  1  7  5  2  0  3  1  4  0  1  0  7]
 [ 0  4  0  0  5  1  0  1  0  0  1  0  4  0  1  1]
 [ 1 11  2  5  7  8  2  5  1  0  2  0  4  0  0  0]
 [ 1  4  3  3  2  2  2  1  0  0  0  3  3  1  2  0]
 [ 0  6  6 13  6 12  4  7  2  0  6  2  1  1  0  2]
 [ 1  3  0  0  1  1  1  0 14  8  9  5 17  1  3  1]
 [ 4  4  1  3  1  3  1  1  9  9  3  5 12  0  2  0]
 [ 0  6  5  3  1  1  2  1  5  3 12 10  2  0  6  2]
 [ 1  6  5  0  2  2  2  2  2  5  5 19  5  2  4  3]
 [ 1  7  0  1  4  1  0  0  3  5  4  4 15  0  2  1]
 [ 0  1  4  2  5  4  3  1  3  3  7  3 10  3  2  2]
 [ 2  2  3  0  9  0  0  0  5  2  1  6  4  0  3  1]
 [ 1  2  7  9  3  1  8  2  1  2  5  4  2  0  2  4]]
F1 Score: 0.17508986319069092
Recall: 0.1902226305499473
Precision: 0.18738734732114243
Encoder: LabelEncoder, Scaler: MinMaxScaler, T

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.20318237454100369
Confusion Matrix:
 [[ 8 11  4  2  0  1  0  2  2  2  0  2  4  8  0  1]
 [ 3 21  4  5  0  6  0  2  1  0  3  1  1  3  1  1]
 [ 0  1 23 11  0  3  0  7  2  0  4  0  1  1  0  3]
 [ 3  4  8 21  0  4  0  7  0  2  1  4  0  1  0  7]
 [ 5  6  0  0  0  1  0  1  0  1  1  0  2  0  0  1]
 [ 3 16  4  6  0  4  0  8  1  1  2  0  3  0  0  0]
 [ 2  5  7  2  0  1  0  2  0  0  1  3  2  1  1  0]
 [ 4  9 11 12  0  3  0 16  2  0  6  2  1  1  0  1]
 [ 2  3  0  1  0  1  0  0 15 15 12  6  5  4  0  1]
 [ 8  7  2  4  0  0  0  2 12  9  5  4  4  1  0  0]
 [ 3  6  6  3  0  0  0  3  5  2 16 10  0  3  0  2]
 [ 3  7  7  0  0  0  0  4  5  5  7 17  2  3  1  4]
 [10  7  0  1  0  1  0  0  4  8  4  4  7  0  1  1]
 [ 3  2  6  3  0  4  0  0  5  3 11  2  5  6  0  3]
 [11  4  3  0  0  0  0  0  8  2  2  5  2  0  0  1]
 [ 3  5 15  8  0  1  0  3  1  2  6  3  1  2  0  3]]
F1 Score: 0.16264462336762253
Recall: 0.17977634592402786
Precision: 0.15876297590572297
Encoder: LabelEncoder, Scaler: MinMaxScaler, 

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy: 0.18337408312958436
Confusion Matrix:
 [[ 1  2  1  1  0  3  1  1  1  0  0  1  4  1  0  1]
 [ 1  6  1  3  3  4  0  1  0  0  1  1  1  0  0  0]
 [ 0  1  8  6  1  2  4  2  1  0  2  0  0  0  1  1]
 [ 0  2  4 12  0  1  0  1  0  1  0  1  0  1  0  1]
 [ 0  3  0  1  2  2  0  0  0  0  0  0  2  0  0  1]
 [ 1  7  0  2  4  4  2  4  0  0  1  0  1  0  0  0]
 [ 1  3  2  0  1  2  2  1  0  0  0  2  0  0  1  0]
 [ 0  4  4  7  2  8  0  5  0  0  2  1  0  1  0  1]
 [ 0  1  0  0  1  1  0  0  7  3  4  3  8  0  1  0]
 [ 1  1  1  3  1  0  0  1  8  3  1  3  4  0  2  0]
 [ 0  2  2  1  2  1  1  2  2  0  4  7  0  0  2  1]
 [ 0  2  3  0  1  2  2  1  3  1  3 11  2  1  6  2]
 [ 0  3  0  1  1  0  0  0  3  3  4  3  9  1  0  1]
 [ 0  1  3  2  2  2  1  0  5  0  4  3  5  0  4  1]
 [ 1  1  3  0  3  0  0  0  4  1  1  3  2  0  1  0]
 [ 1  0  4  5  0  1  3  1  0  1  2  2  0  0  2  0]]
F1 Score: 0.15842149195207894
Recall: 0.17777001694027555
Precision: 0.15630722828633745
Encoder: LabelEncoder, Scaler: MinMaxScaler, 

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.19070904645476772
Confusion Matrix:
 [[ 3  5  1  1  0  1  0  2  2  0  0  0  2  0  0  1]
 [ 2  8  1  3  0  4  0  2  0  0  1  0  1  0  0  0]
 [ 0  1 12  8  0  2  0  2  1  0  2  0  0  0  0  1]
 [ 0  2  3 13  0  1  0  1  0  1  0  0  0  1  0  2]
 [ 1  4  0  1  0  2  0  0  0  1  0  0  1  0  0  1]
 [ 3  9  2  3  0  1  0  6  1  0  1  0  0  0  0  0]
 [ 1  4  4  0  0  0  0  3  0  0  0  3  0  0  0  0]
 [ 1  6  5 10  0  2  0  7  0  0  2  0  0  1  0  1]
 [ 1  1  0  1  0  0  0  0  8  8  5  3  2  0  0  0]
 [ 4  3  1  2  0  0  0  2  9  3  2  2  0  1  0  0]
 [ 1  3  2  2  0  0  0  2  2  0  5  7  0  1  0  2]
 [ 3  3  5  0  0  0  0  3  3  2  4 11  0  2  1  3]
 [ 5  3  0  1  0  0  0  0  4  4  4  3  4  0  0  1]
 [ 2  1  3  2  0  3  0  0  6  1  8  1  2  3  0  1]
 [ 5  1  3  0  0  0  0  0  4  2  1  4  0  0  0  0]
 [ 2  1  7  6  0  0  0  1  0  1  2  2  0  0  0  0]]
F1 Score: 0.14745269874465872
Recall: 0.17453499964275826
Precision: 0.15312308807517166
Encoder: LabelEncoder, Scaler: RobustScaler, 

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy: 0.2146938775510204
Confusion Matrix:
 [[13 11  4  1 11  2  6  3  0  6  2  4  7  4  1  3]
 [ 3 27  0  6 10 10  6  2  2  2  3  1  4  3  2  2]
 [ 2  1 24 12  5  1 14  9  2  0  8  1  1  0  0  6]
 [ 2  4  4 37  3  8 10 10  1  1  3  3  0  0  1  7]
 [ 1  7  0  2  6  1  2  1  1  2  2  0  5  0  1  1]
 [ 1 12  4  2 10 12  4 10  2  2  2  1  6  0  0  0]
 [ 1  5  7  3  2  2  7  3  0  0  0  3  3  1  3  1]
 [ 3  7 11 13  6 11  7 20  1  0 10  2  1  2  0  5]
 [ 5  5  0  1  2  0  2  0 17 13 12  7 21  2  6  3]
 [ 9  5  1  3  1  1  6  1 16 13  4  6 16  0  4  3]
 [ 3  3  8  8  2  0  4  2  7  1 22 18  4  0  9  3]
 [ 5  6  5  4  3  2  3  3  2  3  8 26  5  4  7  4]
 [ 3  7  0  0  6  1  1  1  8  6  1  4 17  3  3  2]
 [ 1  3  4  2  7  3  7  0  6  4 10  2  7  5  4  5]
 [ 9  1  4  0  8  0  3  0  5  4  2  6  6  2  3  6]
 [ 0  9 10 11  3  3  6  3  2  2  8  5  2  1  4 14]]
F1 Score: 0.20036033906742293
Recall: 0.2067657091633224
Precision: 0.2086652994696827
Encoder: LabelEncoder, Scaler: RobustScaler, Tes

Accuracy: 0.22040816326530613
Confusion Matrix:
 [[19 15  6  1  0  3  0  3  0  6  3  4  5  8  1  4]
 [ 7 31  4  7  0 11  0  5  2  2  4  1  2  5  0  2]
 [ 4  1 34 14  0  3  0  8  2  1  9  0  0  2  0  8]
 [ 3  7 12 40  0  6  0 11  1  1  3  4  0  0  0  6]
 [ 4 10  2  2  1  0  0  1  1  2  2  0  4  2  0  1]
 [ 5 20  7  3  1  7  0 12  1  2  2  1  4  3  0  0]
 [ 2  8 12  3  0  0  0  5  2  1  1  3  1  2  0  1]
 [ 6 10 17 17  0  7  0 20  1  0  9  2  2  2  0  6]
 [ 9  6  0  1  0  1  0  0 21 13 15  7 14  6  0  3]
 [14  8  3  3  0  1  1  2 16 11  5  6 11  5  0  3]
 [ 6  5 10  8  0  0  0  2  7  1 27 18  2  5  0  3]
 [10  8  6  2  0  0  0  4  3  4 10 25  2  7  2  7]
 [10  9  0  0  0  1  0  1  9  9  3  5  9  4  2  1]
 [ 5  3  7  4  0  2  0  0  8  5 11  3  7 10  0  5]
 [18  1  6  0  0  1  0  0  5  4  2  7  5  4  0  6]
 [ 5 11 16 10  0  1  0  3  1  3  9  4  2  3  0 15]]
F1 Score: 0.1833068922072983
Recall: 0.19674814708228533
Precision: 0.20559397295265053
Encoder: LabelEncoder, Scaler: RobustScaler, T

Accuracy: 0.21909424724602203
Confusion Matrix:
 [[10  5  1  1  3  2  5  3  0  1  0  4  5  3  1  3]
 [ 2 17  0  3  6  4  3  4  0  2  3  0  2  2  2  2]
 [ 0  0 15  8  4  1 10  6  1  0  5  0  1  1  1  3]
 [ 2  3  1 23  1  5  9  5  1  1  2  3  0  0  1  5]
 [ 2  4  0  1  5  0  1  0  0  0  1  0  3  0  0  1]
 [ 1 10  2  3  7  8  2  8  1  0  2  0  4  0  0  0]
 [ 2  4  2  1  2  1  5  2  0  0  0  3  3  1  1  0]
 [ 1  6  6 11  5  7  4 15  1  0  6  2  1  1  0  2]
 [ 3  2  0  1  1  0  2  0 12 11  8  5 15  0  3  2]
 [ 9  4  1  2  1  1  3  1 10  9  3  3  8  0  2  1]
 [ 2  4  5  6  1  0  3  1  3  3 13 10  2  0  5  1]
 [ 7  3  5  0  2  2  3  1  2  1  7 18  4  3  3  4]
 [ 3  7  0  0  5  1  0  1  7  2  3  3 13  1  1  1]
 [ 0  1  1  3  5  2  6  0  6  2  5  2  9  5  2  4]
 [ 6  1  1  0  7  0  1  0  4  2  1  5  5  0  2  3]
 [ 0  1  6  8  3  1 10  3  2  1  4  3  2  0  0  9]]
F1 Score: 0.20707921470937468
Recall: 0.2158373436341
Precision: 0.22124470596562068
Encoder: LabelEncoder, Scaler: RobustScaler, Test

Accuracy: 0.2215422276621787
Confusion Matrix:
 [[13  7  2  2  0  2  0  3  0  1  0  5  4  6  0  2]
 [ 5 18  2  4  0  5  0  6  0  2  3  0  1  3  1  2]
 [ 1  0 23  9  0  3  0  7  2  0  5  0  1  2  0  3]
 [ 2  5  8 25  0  3  0  6  1  1  2  4  0  0  0  5]
 [ 5  6  0  1  0  0  0  0  0  0  1  0  3  1  0  1]
 [ 4 15  3  5  1  3  0  9  1  0  2  0  4  1  0  0]
 [ 2  6  5  3  0  0  0  2  1  2  0  3  0  2  1  0]
 [ 3  7 10 11  0  3  0 19  1  0  6  2  1  1  1  3]
 [ 3  3  0  1  0  1  0  0 15 14 10  5  7  3  1  2]
 [11  6  1  2  0  1  1  2 13  7  4  3  6  0  0  1]
 [ 5  5  8  5  0  0  0  1  3  3 15  9  0  3  0  2]
 [ 9  5  6  0  0  0  0  2  3  3  7 19  2  3  1  5]
 [10  7  0  0  0  1  0  1  7  6  3  3  6  2  1  1]
 [ 3  2  2  4  0  2  0  0  6  5  7  3  6  9  0  4]
 [13  1  2  0  0  0  0  0  4  3  1  7  3  1  0  3]
 [ 6  2 12  9  0  1  0  4  2  1  4  2  1  0  0  9]]
F1 Score: 0.18100792797253315
Recall: 0.19632674722505264
Precision: 0.1767351144822113
Encoder: LabelEncoder, Scaler: RobustScaler, Te

Accuracy: 0.2078239608801956
Confusion Matrix:
 [[ 3  0  1  1  3  2  1  1  0  0  0  1  2  2  0  1]
 [ 1  7  0  0  4  3  2  3  0  0  1  0  1  0  0  0]
 [ 0  0  8  7  1  1  2  4  0  0  2  0  0  0  2  2]
 [ 0  2  2 13  0  1  2  1  0  1  0  1  0  0  0  1]
 [ 0  3  0  1  4  0  0  0  0  0  0  0  2  0  0  1]
 [ 1  6  1  1  5  4  0  6  0  0  1  0  0  0  1  0]
 [ 1  3  2  0  1  1  3  1  0  1  0  2  0  0  0  0]
 [ 1  2  6  7  4  4  1  6  0  0  1  1  0  1  0  1]
 [ 0  1  0  1  1  0  1  0  6  5  3  3  7  0  1  0]
 [ 2  2  1  2  0  0  2  0  8  2  1  2  3  2  1  1]
 [ 2  2  2  2  2  0  1  1  0  1  4  8  0  0  2  0]
 [ 1  1  3  1  1  1  3  0  2  1  3 11  2  3  5  2]
 [ 0  3  0  0  1  0  1  1  4  2  3  3  8  1  1  1]
 [ 0  1  2  1  3  2  2  0  4  1  2  2  5  3  3  2]
 [ 2  1  2  0  2  0  0  0  2  2  0  2  3  0  1  3]
 [ 0  2  6  5  0  1  1  1  0  0  2  1  0  0  1  2]]
F1 Score: 0.19315454946657667
Recall: 0.21237367358057013
Precision: 0.19590289094924646
Encoder: LabelEncoder, Scaler: RobustScaler, T

Accuracy: 0.21026894865525672
Confusion Matrix:
 [[ 5  4  1  2  0  1  0  1  0  0  0  1  1  1  0  1]
 [ 2  8  2  0  0  3  0  4  0  0  1  0  1  0  0  1]
 [ 0  0 10  8  0  1  0  4  1  0  2  0  0  1  0  2]
 [ 0  2  3 15  0  0  0  1  0  1  0  1  0  0  0  1]
 [ 0  7  0  1  0  0  0  0  0  1  0  0  1  0  0  1]
 [ 3  9  1  2  0  2  0  7  0  0  1  0  0  1  0  0]
 [ 1  5  4  0  0  0  0  2  0  1  0  2  0  0  0  0]
 [ 1  5  6  8  0  3  0  8  0  0  1  0  0  1  0  2]
 [ 0  2  0  1  0  0  0  0  7  8  4  3  3  1  0  0]
 [ 3  3  2  2  0  0  0  0 11  3  1  2  1  0  0  1]
 [ 4  3  2  2  0  0  0  1  0  1  6  6  0  1  0  1]
 [ 4  2  4  2  0  0  0  0  3  2  4 11  1  3  1  3]
 [ 5  3  0  0  0  0  0  1  5  4  4  3  2  1  0  1]
 [ 0  1  2  2  0  2  0  0  5  2  5  2  4  6  0  2]
 [ 4  2  2  0  0  0  0  0  2  3  0  3  1  0  0  3]
 [ 1  2  7  5  0  0  0  1  0  0  2  1  0  0  0  3]]
F1 Score: 0.17020507564501297
Recall: 0.19662083606049124
Precision: 0.16962305394276994
Encoder: LabelEncoder, Scaler: No Scale, Test

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy: 0.15183673469387754
Confusion Matrix:
 [[ 2 14  3  7 12  8  0  1  2  3  4  3 14  1  3  1]
 [ 0 25  3  3 12 15  0  3  4  2  6  2  4  0  3  1]
 [ 0  2 22 18  6 13  2  8  2  0  6  2  2  0  3  0]
 [ 1 10 10 24  3 19  3  7  1  2  6  3  1  0  2  2]
 [ 0  8  2  1  2  3  0  2  1  2  2  0  6  0  3  0]
 [ 0 16  5  4 10 11  0  7  1  1  3  1  8  0  1  0]
 [ 0  5 10  6  3  3  0  2  0  0  1  2  4  0  5  0]
 [ 0 11 16 13  9 19  0 12  4  1  3  7  3  0  1  0]
 [ 1  8  2  2  2  3  0  1 16 16 10  5 21  1  6  2]
 [ 0  9  1  5  3  2  0  3 16 17  5  5 21  0  2  0]
 [ 1 10 13 11  5  4  2  0 11  3 15 10  2  0  6  1]
 [ 1 10  6  3  6  3  1  3  9  8  5 11 12  0 10  2]
 [ 2  7  0  2  3  2  0  0  1 10  4  3 21  0  8  0]
 [ 1  8  6  3  7  5  2  1  4  3  9  2 10  0  8  1]
 [ 0  3  7  1  4  3  0  1  6  4  2  5 15  0  8  0]
 [ 2 16 11 11  8 10  1  1  2  6  7  1  3  0  4  0]]
F1 Score: 0.12614739267989522
Recall: 0.1432410575649074
Precision: 0.13088882700926827
Encoder: LabelEncoder, Scaler: No Scale, Test 

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.1673469387755102
Confusion Matrix:
 [[12 22  6  5  0  3  0  3  6  2  6  0 10  1  1  1]
 [ 5 35  4  4  0  7  0  7  7  1  6  0  4  0  2  1]
 [ 3  4 30 16  0  3  0 13  4  0  6  0  1  2  0  4]
 [ 4 11 20 22  0  5  0 14  2  2  7  1  0  2  0  4]
 [ 3  8  3  0  0  2  0  4  3  0  2  0  6  1  0  0]
 [ 5 20  9  3  0  3  0 14  1  2  3  1  6  0  0  1]
 [ 4  5 15  5  0  1  0  2  0  1  1  3  3  0  1  0]
 [ 5 16 20 11  0  7  0 17  4  1  7  5  4  1  0  1]
 [ 3  8  4  1  0  0  0  3 27 14 11  2 16  1  4  2]
 [ 4 11  3  3  0  0  0  4 27 13  6  4 12  0  1  1]
 [ 5  8 16  7  0  0  0  3 14  1 20  5  2  1  3  9]
 [14  9  8  2  0  0  0  6 14  8  7  7  7  1  2  5]
 [11  9  0  1  0  1  0  0  5  8  5  5 14  1  3  0]
 [10  8 12  2  0  2  0  5  6  4 10  2  7  1  0  1]
 [ 9  4  8  0  0  1  0  1 13  3  3  3 11  1  1  1]
 [ 7 17 20 10  0  3  0  3  3  5  8  1  3  0  0  3]]
F1 Score: 0.1281868228021223
Recall: 0.1488568937764001
Precision: 0.12932482939792422
Encoder: LabelEncoder, Scaler: No Scale, Test Si

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy: 0.16156670746634028
Confusion Matrix:
 [[ 4  7  1  1  6  5  3  2  2  3  1  2  9  0  1  0]
 [ 0 21  3  1  5  4  1  6  1  3  3  0  3  0  1  0]
 [ 0  1 11  1  5  5  9 17  1  1  4  0  1  0  0  0]
 [ 1  8  4  5  0  9  5 15  1  3  5  2  0  0  1  3]
 [ 0  5  0  0  4  2  0  1  0  0  1  0  5  0  0  0]
 [ 1 11  4  2  7  6  2  7  0  0  2  0  5  0  1  0]
 [ 0  4  4  1  4  0  2  3  0  0  1  2  4  0  2  0]
 [ 0  9  8  3  7  7  5 14  2  1  4  5  3  0  0  0]
 [ 2  2  1  1  2  1  2  1 10 14 10  4 11  0  4  0]
 [ 0  7  0  3  0  0  2  3  5 19  4  2 12  0  1  0]
 [ 1  5  6  4  3  0  7  3  3  6 10  7  2  0  1  1]
 [ 1  5  4  1  9  1  2  4  4  9  4  9  9  1  2  0]
 [ 0  7  0  1  3  1  0  0  1 10  4  2 15  0  4  0]
 [ 1  2  2  2  8  2  3  4  3  4  9  2  9  0  2  0]
 [ 0  2  2  0  3  1  1  0  4  4  2  2 15  0  2  0]
 [ 2  6  6  6  7  2  7  3  3  2  7  0  2  0  0  0]]
F1 Score: 0.13866706010394816
Recall: 0.15923262014728656
Precision: 0.14720373652251942
Encoder: LabelEncoder, Scaler: No Scale, Test

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.1689106487148103
Confusion Matrix:
 [[ 8 13  3  2  0  3  0  2  4  1  2  0  8  0  1  0]
 [ 2 24  3  3  0  5  0  4  4  0  3  0  2  0  2  0]
 [ 2  2 19 10  0  3  0 10  2  0  5  0  0  0  1  2]
 [ 2  8 10 14  0  3  0  8  1  2  6  1  0  0  1  6]
 [ 2  6  0  0  0  2  0  2  0  0  1  0  5  0  0  0]
 [ 4 16  6  3  0  3  0  9  0  1  2  0  3  0  0  1]
 [ 3  5  6  2  0  1  0  2  0  1  1  3  2  0  1  0]
 [ 2 13 12  6  0  5  0 12  3  1  7  1  3  0  1  2]
 [ 5  3  2  1  0  0  0  2 18  9 11  2  7  0  4  1]
 [ 4  7  3  2  0  0  0  3 15 12  4  2  4  0  2  0]
 [ 4  5 10  4  0  0  0  2  8  1 11  6  0  0  1  7]
 [ 8  6  4  2  0  0  0  4 10  7  7  5  5  1  2  4]
 [10  8  0  1  0  1  0  0  2  8  5  3  8  0  2  0]
 [ 9  4  6  2  0  1  0  4  4  4  9  2  6  0  0  2]
 [ 7  4  3  0  0  0  0  0  9  2  3  2  6  0  1  1]
 [ 4  7 14  7  0  2  0  2  1  4  7  0  2  0  0  3]]
F1 Score: 0.13145168250535766
Recall: 0.15203647468071688
Precision: 0.12819655927575502
Encoder: LabelEncoder, Scaler: No Scale, Test 

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy: 0.13447432762836187
Confusion Matrix:
 [[ 0  4  1  1  2  4  0  0  0  1  0  1  4  0  0  0]
 [ 0  3  1  1  7  3  0  3  0  2  1  0  1  0  0  0]
 [ 0  1  6  6  1  5  2  3  1  0  3  0  0  0  1  0]
 [ 0  2  5  6  0  1  1  4  0  0  2  0  1  0  0  2]
 [ 0  4  0  0  1  2  0  1  0  0  0  0  2  0  1  0]
 [ 0  5  1  1  6  3  2  3  0  0  1  0  2  0  2  0]
 [ 0  3  3  1  2  1  0  1  0  0  1  2  0  0  1  0]
 [ 0  5  6  4  7  3  1  5  0  0  1  2  0  0  0  1]
 [ 0  0  0  0  1  0  0  1  4  7  7  2  5  0  2  0]
 [ 0  2  0  1  0  0  0  2  2 11  2  2  5  0  2  0]
 [ 0  3  4  2  2  0  3  1  2  1  2  4  1  0  0  2]
 [ 2  2  3  2  2  2  1  1  2  5  3  5  1  1  8  0]
 [ 0  3  0  1  0  0  0  0  0  7  4  2  7  0  5  0]
 [ 0  2  2  0  4  1  2  1  3  2  7  1  4  1  3  0]
 [ 0  1  2  0  1  0  1  0  2  3  2  1  6  0  1  0]
 [ 0  2  3  6  1  2  2  1  0  2  2  0  1  0  0  0]]
F1 Score: 0.11402689859004239
Recall: 0.12377555195443127
Precision: 0.14100453653265754
Encoder: LabelEncoder, Scaler: No Scale, Test

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.1466992665036675
Confusion Matrix:
 [[ 2  5  1  1  0  2  0  2  1  0  1  0  3  0  0  0]
 [ 0  9  1  4  0  2  0  1  2  0  1  0  1  0  0  1]
 [ 0  2  9  7  0  0  0  6  1  0  3  0  0  0  1  0]
 [ 0  2  5  8  0  1  0  3  0  1  2  0  0  0  0  2]
 [ 1  4  0  0  0  2  0  2  0  0  0  0  2  0  0  0]
 [ 4  8  3  1  0  1  0  6  0  0  1  0  1  0  0  1]
 [ 1  4  4  1  0  0  0  1  0  0  1  2  1  0  0  0]
 [ 3  6  7  5  0  4  0  6  0  0  2  1  0  0  0  1]
 [ 3  1  0  0  0  0  0  1  9  6  7  0  1  0  1  0]
 [ 2  3  0  1  0  0  0  2  9  6  3  1  1  0  1  0]
 [ 2  5  6  2  0  0  0  1  3  0  2  3  0  0  0  3]
 [ 6  3  3  2  0  0  0  3  6  2  4  3  3  0  1  4]
 [ 6  3  0  1  0  0  0  0  2  5  5  2  5  0  0  0]
 [ 4  2  4  1  0  1  0  1  3  2 10  0  3  0  0  2]
 [ 4  2  3  0  0  0  0  0  4  2  2  2  1  0  0  0]
 [ 2  2  6  5  0  1  0  2  2  0  2  0  0  0  0  0]]
F1 Score: 0.11378815088186447
Recall: 0.1382812210937211
Precision: 0.10991620388225876
Encoder: OneHotEncoder, Scaler: StandardScaler,

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


ValueError: ignored

In [ ]:
wandb.finish()